apiVersion: apps/v1
kind: Deployment
metadata:
  name: udargram-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udargram-frontend
  template:
    metadata:
      labels:
        app: udargram-frontend
        api: external
    spec:
      containers:
        - image: canthuy/udagram-frontend
          name: udargram-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
      restartPolicy: Always
