apiVersion: apps/v1
kind: Deployment
metadata:
  name: udargam-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - image: canthuy/udagram-api-feed
          name: udargam-api-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          env:
            - name: NODE_OPTIONS
              value: '--max-old-space-size=4096'
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: POSTGRESS_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESS_DB
            - name: POSTGRESS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESS_HOST
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_PASSWORD
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_USERNAME
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_secret_access_key
            - name: AWS_SECRET_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_secret_access_token
      restartPolicy: Always
